In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1],4) 
        self.weights2 = np.random.rand(4,1)                 
        self.y = y
        self.output = np.zeros(y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        return self.output

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

if __name__ == "__main__":
    X = np.array([[0,0,1],
                  [0,1,1],
                  [1,0,1],
                  [1,1,1]])
    y = np.array([[0],[1],[1],[0]])
    nn = NeuralNetwork(X,y)

    for i in range(1500):
        print(nn.feedforward())
        nn.backprop()


[[0.6715983 ]
 [0.69459381]
 [0.71134991]
 [0.72427201]]
[[0.51725194]
 [0.51751655]
 [0.52620475]
 [0.52549503]]
[[0.50195369]
 [0.49999113]
 [0.50725267]
 [0.50508738]]
[[0.50448722]
 [0.50325038]
 [0.51030758]
 [0.50855938]]
[[0.50397316]
 [0.50295597]
 [0.50960399]
 [0.5079503 ]]
[[0.50398653]
 [0.5032762 ]
 [0.50955525]
 [0.50804995]]
[[0.50390738]
 [0.50348868]
 [0.50939637]
 [0.50802822]]
[[0.5038429 ]
 [0.50371888]
 [0.50925984]
 [0.50802912]]
[[0.50377421]
 [0.50394526]
 [0.50912259]
 [0.50802777]]
[[0.50370431]
 [0.50417178]
 [0.50898856]
 [0.50802862]]
[[0.5036324 ]
 [0.50439799]
 [0.508857  ]
 [0.50803103]]
[[0.50355833]
 [0.50462419]
 [0.50872796]
 [0.50803523]]
[[0.50348183]
 [0.50485055]
 [0.50860139]
 [0.5080413 ]]
[[0.50340264]
 [0.50507727]
 [0.50847723]
 [0.50804938]]
[[0.50332051]
 [0.50530454]
 [0.50835546]
 [0.50805957]]
[[0.50323515]
 [0.50553256]
 [0.50823603]
 [0.50807198]]
[[0.50314629]
 [0.50576152]
 [0.50811891]
 [0.50808675]]
[[0.50305365]
 [0.50599161]
 [0